const initialVideoData = [
  {
    id: "gMaB-fG4u4g",
    title: "전신 다이어트 최고의 운동 [칼소폭 찐 핵핵매운맛]",
    part: "전신",
    category: "all",
    channelName: "ThankyouBUBU",
    url: "https://www.youtube.com/embed/gMaB-fG4u4g",
    thumbnail: "https://img.youtube.com/vi/gMaB-fG4u4g/hqdefault.jpg",
    views: 1500, // 예시 조회수
  },
  {
    id: "swRNeYw1JkY",
    title: "하루 15분! 전신 칼로리 불태우는 다이어트 운동",
    part: "전신",
    category: "all",
    channelName: "ThankyouBUBU",
    url: "https://www.youtube.com/embed/swRNeYw1JkY",
    thumbnail: "https://img.youtube.com/vi/swRNeYw1JkY/hqdefault.jpg",
    views: 1200,
  },
  {
    id: "54tTYO-vU2E",
    title:
      "상체 다이어트 최고의 운동 BEST [팔뚝살/겨드랑이살/등살/가슴어깨라인]",
    part: "상체",
    category: "upper",
    channelName: "ThankyouBUBU",
    url: "https://www.youtube.com/embed/54tTYO-vU2E",
    thumbnail: "https://img.youtube.com/vi/54tTYO-vU2E/hqdefault.jpg",
    views: 2200,
  },
  {
    id: "QqqZH3j_vH0",
    title: "상체비만 다이어트 최고의 운동 [상체 핵매운맛]",
    part: "상체",
    category: "upper",
    channelName: "ThankyouBUBU",
    url: "https://www.youtube.com/embed/QqqZH3j_vH0",
    thumbnail: "https://img.youtube.com/vi/QqqZH3j_vH0/hqdefault.jpg",
    views: 980,
  },
  {
    id: "tzN6ypk6Sps",
    title: "하체운동이 중요한 이유? 이것만 보고 따라하자 ! [하체운동 교과서]",
    part: "하체",
    category: "lower",
    channelName: "김강민",
    url: "https://www.youtube.com/embed/tzN6ypk6Sps",
    thumbnail: "https://img.youtube.com/vi/tzN6ypk6Sps/hqdefault.jpg",
    views: 3100,
  },
  {
    id: "u5OgcZdNbMo",
    title: "저는 하체 식주의자 입니다",
    part: "하체",
    channelName: "GYM종국",
    category: "lower",
    url: "https://www.youtube.com/embed/u5OgcZdNbMo",
    thumbnail: "https://img.youtube.com/vi/u5OgcZdNbMo/hqdefault.jpg",
    views: 4500,
  },
  {
    id: "PjGcOP-TQPE",
    title: "11자복근 복부 최고의 운동 [복근 핵매운맛]",
    part: "복부",
    category: "abs",
    channelName: "ThankyouBUBU",
    url: "https://www.youtube.com/embed/PjGcOP-TQPE",
    thumbnail: "https://img.youtube.com/vi/PjGcOP-TQPE/hqdefault.jpg",
    views: 1800,
  },
  {
    id: "7TLk7pscICk",
    title: "(Sub)누워서하는 5분 복부운동!! 효과보장! (매일 2주만 해보세요!)",
    part: "복부",
    category: "abs",
    channelName: "SomiFit",
    url: "https://www.youtube.com/embed/7TLk7pscICk",
    thumbnail: "https://img.youtube.com/vi/7TLk7pscICk/hqdefault.jpg",
    views: 2500,
  },
];
